name: Release
on:
  release:
    types: [ created ]
jobs:
  build-arm:
    runs-on: [self-hosted, linux, arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tags
        id: tags
        run: |
          echo ::set-output name=image::${{ secrets.DOCKER_HUB_USERNAME }}/action-runner
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.tags.outputs.image }}:latest
            ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
