name: Build action-runner
on:
  release:
    types: [ created, edited ]
jobs:
  build:
    strategy:
      matrix:
        version: [ 2.311.0 ]
        arch: [ arm, amd64, arm64 ]
    runs-on: [self-hosted, linux, arm]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set tags
        id: tags
        run: |
          echo "{arch}={${{ matrix.arch }}}" >> $GITHUB_OUTPUT
          echo "{runner}={${{ matrix.version }}}" >> $GITHUB_OUTPUT
          echo "{image}={ghcr.io/${{ github.repository_owner }}/runner-image-arm}" >> $GITHUB_OUTPUT
          echo "{tag}={${GITHUB_REF#refs/tags/v}}" >> $GITHUB_OUTPUT
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker build \
            --tag ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }} \
            --build-arg RUNNER_VERSION=${{ steps.tags.outputs.runner }} \
            --build-arg RUNNER_ARCH=${{ steps.tags.outputs.arch }} \
            --file Dockerfile-bookworm .
      - name: Push
        run: |
          docker push ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.tag }}
  manifest:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Set tags
        id: tags
        run: |
          echo "{manifest}={ghcr.io/${{ github.repository_owner }}/runner-image}" >> $GITHUB_OUTPUT
          echo "{tag}={${GITHUB_REF#refs/tags/v}}" >> $GITHUB_OUTPUT
      - name: Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Manifest
        run: |
          docker manifest create ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            --amend ${{ steps.tags.outputs.manifest }}-arm:${{ steps.tags.outputs.tag }} \
            --amend ${{ steps.tags.outputs.manifest }}-arm64:${{ steps.tags.outputs.tag }}
            --amend ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch arm64 ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-arm64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch arm ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-arm:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch amd64 ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
          docker manifest push ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }}
