name: Build action-runner (test)
on:
  workflow_dispatch:

jobs:
  build-image:
    strategy:
      matrix:
        arch: [arm, arm64, amd64]
    uses: mutablelogic/docker-action-runner/.github/workflows/build-image.yml@main
    with:
      target: ${{ matrix.target }}
