name: Build action-runner (test)
on:
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        version: [ 2.311.0 ]
        platform: [ linux ]
        arch: [ arm64, amd64 ]
    uses: mutablelogic/docker-action-runner/.github/workflows/build-image.yaml@main
    with:
      version: ${{ matrix.version }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}
