name: Make arm64 and amd64 docker images
on:
  workflow_dispatch:

jobs:
  build-images:
    strategy:
      matrix:
        version: [ 2.311.0 ]
        platform: [ linux ]
        arch: [ arm64, amd64 ]
    uses: mutablelogic/docker-action-runner/.github/workflows/build-image.yaml@main
    with:
      version: ${{ matrix.version }}
      platform: ${{ matrix.platform }}
      arch: ${{ matrix.arch }}
  create-manifest:
    needs:
      - build-images
    runs-on: ubuntu-latest
    steps:
      - name: Set tags
        id: tags
        run: |
          echo "manifest=ghcr.io/${{ github.repository_owner }}/runner-image" >> $GITHUB_OUTPUT
          echo "tag=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Manifest
        run: |
          docker manifest create ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            --amend ${{ steps.tags.outputs.manifest }}-arm64:${{ steps.tags.outputs.tag }} \
            --amend ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch arm64 ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-arm64:${{ steps.tags.outputs.tag }}
          docker manifest annotate --arch amd64 ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }} \
            ${{ steps.tags.outputs.manifest }}-amd64:${{ steps.tags.outputs.tag }}
          docker manifest push ${{ steps.tags.outputs.manifest }}:${{ steps.tags.outputs.tag }}
